version: '3.8'
services:
  redis:
    image: "redis:alpine" 
    container_name: redis_cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data 
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"] 
    restart: unless-stopped

volumes:
  redis_data:
